export {
  fetchAdminCourses,
  fetchOrders,
  fetchAssessments,
  fetchAdminDashboard,
  fetchAdminDashboardStats,
  fetchRecentUsers,
  fetchRecentOrders,
  fetchResources,
  createResource,
  updateResource,
  deleteResource,
  fetchCourseEnrollments,
  assignResourceToEnrollment,
  unassignResourceFromEnrollment,
  fetchModules,
  createModule,
  updateModule,
  deleteModule,
  fetchLessons,
  createLesson,
  updateLesson,
  deleteLesson,
} from "./admin-api";
